### ISSUE TITLE
Why am I getting an empty tree?

### ISSUE THREAD

**Issue by logicfish** [PhilippeSigaud/Pegged#236]
Here's my grammar
https://github.com/logicfish/dn3/blob/master/resources/turtle.peg

The output is showing and empty document.

**Comment by veelo** [comment]
And what is your input?

**Comment by logicfish** [comment]
I've tried various inputs.
https://github.com/logicfish/dn3/blob/master/resources/data.ttl

And examples from this page
https://www.w3.org/TR/turtle/

**Comment by PhilippeSigaud** [comment]
Hi,

Your first rule contains a star-rule

```
turtleDoc <- statement*
```

 so it can match nothing and still succeed globally. That's why you get an
empty tree.

That means in your case that Pegged could not parse a statement, so there
is probably an error in your grammar at a lower level.

I'd advise you to test low-level rules first (subject, object, predicate,
or even the very last ones), with dedicated, specific inputs.



Your IRIREF rule is strangely formated. I'm not sure that

```
[^x00 - x20 \< \> quote {} slash \^ \` backslash]
```
is valid syntax for a [ ] block? I'd advise you to use

```
[^\x00-\x20<>{}\^] / !quote / !backquote / !backslash
```

See https://github.com/PhilippeSigaud/Pegged/wiki/Extended-PEG-Syntax  in
the 'Range of Chars Extension' part.

You have to use `\x41` or `\u0041` for example, not `u41`.

Btw, you do not respect the rules given in your ref
http://www.w3.org/TR/turtle/#grammar-production-turtleDoc, your IRIREF
roule should also exclude pipes (|) and double quotes, if I read that
correctly?

And the same for all your other `[]` rules, `[u00C0-u00D6]` will be
interpreted by Pegged as 'u or 0 or 0 or C or any char between 0 and u, or
0 or 0 or D or 6'. I think you want [\u00C0-\u00D6].

I do not have the time to check the other rules, but you should really
construct small partial texts to test different parts of the parser, by
invoking rules directly.
See:  https://github.com/PhilippeSigaud/Pegged/wiki/Using-a-Grammar  in the
'Calling a Rule' section.

**Comment by logicfish** [comment]
Ok thanks, I will follow your advice. I tried to use "versions" : [ "tracer" ] in my dub.json but it didn't seem to do anything.

**Comment by veelo** [comment]
> I tried to use "versions" : [ "tracer" ] in my dub.json but it didn't seem to do anything.

This can have various reasons. As described in [Grammar Debugging](https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Debugging):

1. peg.d must be recompiled.
2. Tracing must be switched on, the default is `traceNothing()`.
3. You need a `TraceLogger` instance.
4. CT-generated parse trees cannot be traced.
5. The log file needs to be located and examined.

Careful though, logs can quickly fill many GBs of disk space so you probably will want to log only very small snippets of input or selectively turn on logging as described in the wiki.

**Comment by logicfish** [comment]
Ok thanks, that should do the trick.
